### ISSUE TITLE
spawn on join when not wanted

### ISSUE THREAD

**Issue by partridge420x** [MatthewSH/spigot-RandomSpawn#12]
people are spawning on reconnecting, and checking the config im not seeing anything to be able to change that. im running on 1.12.2 and thus far the plugins working apart from not wanting the spawn on join

**Comment by partridge420x** [comment]
running luck perms, random spawn, world edit, essentials X

**Comment by MatthewSH** [comment]
There is a config for it: https://github.com/MatthewSH/spigot-RandomSpawn/blob/master/src/main/resources/config.yml#L12
